name: CI master

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  lint-vala:
    name: Lint vala files
    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint Vala
        run: io.elementary.vala-lint -d .

  lint-blp:
    name: Lint blueprint ui files
    runs-on: ubuntu-latest
    needs: lint-vala

    container:
      image: ubuntu:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update apt cache
        run: apt-get update

      - name: Install blueprint-compiler Blueptint
        run: apt-get install -y blueprint-compiler
        
      - name: Lint Blueprint
        run: blueprint-compiler format -s 2 data/ui/*.blp

  checkers:
    name: Run checkers
    runs-on: ubuntu-latest
    needs: lint-blp

    container:
      image: ubuntu:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update apt cache
        run: apt-get update

      - name: Install python
        run: apt-get install -y python3.12

      - name: Run indentation checker
        run: python3.12 .checkers/indentation_checker.py 

      - name: Run empty lines checker
        run: python3.12 .checkers/empty_lines_checker.py 

  flatter:
    name: Build Repo
    runs-on: ubuntu-latest
    needs: checkers

    container:
      image: ghcr.io/andyholmes/flatter/gnome:master
      options: --privileged

    strategy:
      matrix:
        arch: [aarch64, x86_64]
      fail-fast: false
      max-parallel: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        if: ${{ matrix.arch == 'aarch64' }}
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build 
        uses: andyholmes/flatter@main
        with:
          files: |
            build-aux/flatpak/io.github.Rirusha.Foldy-Devel.json
          arch: ${{ matrix.arch }}
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
          run-tests: true
