name: CI Pull Request

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Lint
      run: io.elementary.vala-lint -d .

  test-build:
    name: Test Build
    runs-on: ubuntu-latest
    needs: lint

    container:
      image: ubuntu:latest
      options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build tools
      run: "echo"

    - name: Install dependecies
      run: "echo"

    - name: Setup
      run: "echo"

    - name: Build
      run: "echo"
